name: "[Ledger Security] Sign container image"
description: "This action is used to sign a container image with a list of tags in keyless mode based on Github OIDC token."

inputs:
  tags:
    description: 'List of tags to sign (based on the output of the docker/metadata-action)'
    required: true
    default: ""
  digest:
    description: 'Digest of the container image to sign (based on the output of the docker/build-push-action)'
    required: true
    default: ""
  

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    - name: Sign containers images
      shell: bash
      run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}