name: "Create GitHub Release"
description: "Create GitHub releases for packages based on version and changelog (Changesets compatible)"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
    default: ${{ github.token }}
  cwd:
    description: "Sets the cwd for the node process"
    required: false
  target_branch:
    description: "The branch or commit SHA where the Git tag will be created from."
    required: false
    default: "main"
runs:
  using: "node20"
  main: "dist/index.js"
