name: "Create GitHub Release"
description: "Create GitHub releases for packages based on version and changelog (Changesets compatible)"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
    default: ${{ github.token }}
  cwd:
    description: "Sets the cwd for the node process"
    required: false
  setupGitUser:
    description: "Sets up the git user (deprecated, not used)"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
