name: "[Ledger Security] Attest an artefact"
description: "Ledger Security Action wrapper to attest an artefact"

inputs:
  subject-path:
    description: "Path to the artefact to attest"
    required: true
    default: "./"
  push-to-registry:
    description: "Push the attestation to the registry"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/attest-build-provenance@v1
      with:
        subject-path: ${{ inputs.subject-path }}
        show-summary: true
        push-to-registry: ${{ inputs.push-to-registry }}
