name: "[Ledger Security] Sign an blob"
description: "This action is used to sign a blob in keyless mode based on Github OIDC token."

inputs:
  path:
    description: 'Path to the artifact or directory with artifacts to sign'
    required: true
    default: ""
  

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    - name: Sign blob
      shell: bash
      run: |
        if [[ -d "${{ inputs.path }}" ]]; then
         for file in ${{ inputs.path }}/*; do
          cosign sign-blob --yes "$file" --bundle "$file.cosign.bundle"
         done
        elif [[ -f "${{ inputs.path }}" ]]; then
         cosign sign-blob --yes ${{ inputs.path }} --bundle ${{ inputs.path }}.cosign.bundle
        else
         echo "Invalid path provided"
         exit 1
        fi
    # TODO: Upload the signature to the artifact store