name: "[Ledger Security] Sign an blob"
description: "This action is used to sign a blob in keyless mode based on Github OIDC token."

inputs:
  path:
    description: 'Path to the artifact to sign'
    required: true
    default: ""
  

runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    - name: Sign blob
      shell: bash
      run: |
        cosign sign-blob ${{ inputs.path }} --bundle cosign.bundle
    # TODO: Upload the signature to the artifact store