name: "[Ledger Security] Upload to JFrog Artifactory"
description: "Ledger Security Action wrapper to login to JFrog"

inputs:
  path:
    description: "Path to the file to upload"
    required: true
    default: "./"
  artifactory_repository:
    description: "Name of the Artifactory Repository to use as destination"
    required: true

runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v4
      id: setup-jfrog-cli
      env:
        JF_URL: "https://artifactory.ledgerlabs.net"
      with:
        oidc-provider-name: github
        oidc-audience: artifactory-3
    - run: |
        jfrog rt u ${{ inputs.path }} ${{ inputs.artifactory_repository}}
      shell: bash