name: "[Ledger Security] Login to JFrog"
description: "Ledger Security Action wrapper to login to JFrog"

runs:
  using: "composite"
  steps:
    - uses: jfrog/setup-jfrog-cli@v4
      id: setup-jfrog-cli
      env:
        JF_URL: "https://artifactory.ledgerlabs.net"
      with:
        oidc-provider-name: github
        oidc-audience: artifactory