name: Publish to Confluence
on: push

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: 'true'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish-action@v5
        with:
          confluenceBaseUrl: https://ledgerhq.atlassian.net/
          confluenceParentId: 5036769289
          atlassianUserName: ${{ secrets.ATLASSIAN_USERNAME }}
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
          folderToPublish: actions
          contentRoot: /actions
          #configFile: .markdown-confluence.json
